apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-alpine
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/adriankabala/argocd-v2-demo.git
    targetRevision: master
    path: manifests/apps/alpine
  destination:
    name: loft-default-virtualcluster-sd-test-argocd
    namespace: child-alpine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
